name: Publish Docker GPU

on:
  push:
    branches:
      - master
    tags:
      - v*
  
  # Triggered by ODM build (after docker push)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Use the repository information of the checked-out code to format docker tags
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: opendronemap/nodeodm
          tag-semver: |
            {{version}}
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.gpu
          platforms: linux/amd64
          push: true
          tags: |
            opendronemap/nodeodm:gpu